# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: An Idyll Place
logo: # Logo image URL
description: Idealized thoughts on crafting software.
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://blog.idyll.io" # The base hostname & protocol for your site
twitter: "https://twitter.com/idyll_code"
github_username: idyll

markdown: kramdown
highlighter: rouge
github: "https://github.com/idyll"
permalink: pretty
paginate: 9
sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# Pages path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  mark:
    name: Mark Madsen
    bio: When I started writing Apps and APIs, phones had buttons!
    gravatar: https://s.gravatar.com/avatar/c2fa64af0819fa9efd35f22c7ce08ae3?s=150
    email: mm@anml.io
    website: http://bog.idyll.io
    github_username: idyll
    twitter_username: "idyll_code"
