# Site settings
title: An Idyll Place
email:
description: > # this means to ignore newlines until "baseurl:"
  Idealized thoughts on crafting software.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.idyll.io" # the base hostname & protocol for your site
twitter_username: idyll_code
github_username:  idyll

# Build settings
markdown: kramdown

highlighter: pygments
github: [Repository metadata]